
services:
  backend:
    build: ./backend
    container_name: advisor-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: advisor-frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend