version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  streamlit:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -c "pip install poetry && poetry install && streamlit run ui/streamlit_app.py"
    ports:
      - "8501:8501"